### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by cam333** [MperorM/website-to-remarkable#1]
Hi, getting an invalid syntax error here and I'm not sure why. any thoughts?

https://github.com/MperorM/website-to-remarkable/blob/8ed393fd4ba5b8797ceed4acb060e3b35486c128/remarkable_functions.py#L24

**Comment by MperorM** [comment]
Oh sorry! This line is using f-strings which is a python feature only present in python 3.6+

try running:
```
python --version
```
if the response is python 2.6 try running the files using
```
python3
```
instead.

I have updated the github repository to reflect python3 is a requirement
